# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "anasa@alpha" do
  version "0.2.0-alpha.4"

  on_arm do
    sha256 "d2c47126dacf0d50c155ff4777f5bed5e67257e091534037676751a3abdfb986"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "1590742ab103e8ffc3f8b9f6b63dd0bb761b90146d4d39df9d8d641f6ee40047"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "anasa.app"
  zap trash: [
    "~/Library/Application Support/com.entro314labs.anasa",
    "~/Library/Caches/com.entro314labs.anasa",
    "~/Library/Preferences/com.entro314labs.anasa.plist",
    "~/Library/Saved Application State/com.entro314labs.anasa.savedState",
    "~/Library/WebKit/com.entro314labs.anasa",
  ]
  caveats <<~EOS
    Alpha builds may not be notarized. If macOS refuses to open
    the app, clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/anasa.app"
  EOS
end
