# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "anasa" do
  version "0.4.1"
  on_arm do
    sha256 "e81e12fe96bd5e8fd0df1b8cfcff8182c376eef7ebca2c0ab1f15cadbc302d9c"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "9b2f5b92caeab37dd1cef060e0ceaba391d2ba848efab90ae4987992032fc8bf"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "anasa.app"
  zap trash: [
    "~/Library/Application Support/com.entro314labs.anasa",
    "~/Library/Caches/com.entro314labs.anasa",
    "~/Library/Preferences/com.entro314labs.anasa.plist",
    "~/Library/Saved Application State/com.entro314labs.anasa.savedState",
    "~/Library/WebKit/com.entro314labs.anasa",
  ]
end
