# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "anasa@beta" do
  version "0.8.0-beta.0"
  on_arm do
    sha256 "c080791ef7d7d82e43435a7ef04c050f9bffec536911756ad70e090e06c06579"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "0a7ff50ba77b7478eac09507b3e8f60bc2e1e63cd764b247401d74fa23c0f708"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "anasa.app"
  zap trash: [
    "~/Library/Application Support/com.entro314labs.anasa",
    "~/Library/Caches/com.entro314labs.anasa",
    "~/Library/Preferences/com.entro314labs.anasa.plist",
    "~/Library/Saved Application State/com.entro314labs.anasa.savedState",
    "~/Library/WebKit/com.entro314labs.anasa",
  ]
  caveats <<~EOS
    Beta builds may not be notarized. If macOS refuses to open
    the app, clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/anasa.app"
  EOS
end
