# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "anasa@beta" do
  version "0.7.0-beta.1"
  on_arm do
    sha256 "4abac28fea4b2560428002a26affa07aee6e728a0ad49420b9ac53cdb55711dd"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "97cda0e0ec4e366dc0ffd8b018f44132a903d830cbb9b24505ac7f1031eb676a"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "anasa.app"
  zap trash: [
    "~/Library/Application Support/com.entro314labs.anasa",
    "~/Library/Caches/com.entro314labs.anasa",
    "~/Library/Preferences/com.entro314labs.anasa.plist",
    "~/Library/Saved Application State/com.entro314labs.anasa.savedState",
    "~/Library/WebKit/com.entro314labs.anasa",
  ]
  caveats <<~EOS
    Beta builds may not be notarized. If macOS refuses to open
    the app, clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/anasa.app"
  EOS
end
