# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "anasa@beta" do
  version "0.5.0-beta.0"
  on_arm do
    sha256 "0e6048311c9d0ba568899e030374e2aa9534d5ca04bf8fb5e9981a9b155f1cc9"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "31f9a48d6c314c4f306caa24a26c55eacd1f598fb81f31b5bc2a9bb383f76ab0"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "anasa.app"
  zap trash: [
    "~/Library/Application Support/com.entro314labs.anasa",
    "~/Library/Caches/com.entro314labs.anasa",
    "~/Library/Preferences/com.entro314labs.anasa.plist",
    "~/Library/Saved Application State/com.entro314labs.anasa.savedState",
    "~/Library/WebKit/com.entro314labs.anasa",
  ]
  caveats <<~EOS
    Beta builds may not be notarized. If macOS refuses to open
    the app, clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/anasa.app"
  EOS
end
