# This file is generated by anasa's release workflow. DO NOT EDIT.
cask "anasa@alpha" do
  version "0.2.0-alpha.2"

  on_arm do
    sha256 "980d004640a11832e69e98cecfd06ee5a2dc2bdffc821adff7c63b028420383b"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "706959d0af4c9bc47eca603e29559d73cc068cc5c39ef87c4e4a468be686571e"
    url "https://github.com/entro314-labs/anasa-releases/releases/download/v#{version}/anasa_#{version}_x64.dmg"
  end

  name "Anasa"
  desc "Local-first Markdown thinking and writing app"
  homepage "https://anasa.md"

  livecheck do
    skip "Updated by the anasa release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  depends_on macos: ">= :ventura"

  app "anasa.app"

  zap trash: [
    "~/Library/Application Support/com.anasa.app",
    "~/Library/Caches/com.anasa.app",
    "~/Library/Preferences/com.anasa.app.plist",
    "~/Library/Saved Application State/com.anasa.app.savedState",
    "~/Library/WebKit/com.anasa.app",
  ]

  caveats <<~CAVEATS
    Alpha/beta builds are not yet notarized. If macOS refuses to open
    the app, clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/anasa.app"
  CAVEATS
end
