# This file was generated by GoReleaser. DO NOT EDIT.
cask "cool-kit" do
  name "cool-kit"
  desc "CLI toolkit for Coolify deployments"
  homepage "https://github.com/entro314-labs/cool-kit"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cool-kit"

  on_macos do
    on_intel do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_macOS_x86_64.tar.gz"
      sha256 "5ef870561f31ae4db5fcc3f29f16d25b42d6f99fbc986c17767aca8d9b3e4e66"
    end
    on_arm do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_macOS_arm64.tar.gz"
      sha256 "dd5a3b54302df8ee9ea32de25cba264e136fe298f75d75b4c38ae0b426ccac82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_linux_x86_64.tar.gz"
      sha256 "fee045b74ac67b97245366924b53327f78201748eabc378faa87bf7eace94482"
    end
    on_arm do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_linux_arm64.tar.gz"
      sha256 "fe9bc4e2efd7e5dc519ad6d0cb635c66b501144b66b7e5f6867aaf67ca2c71df"
    end
  end

  # No zap stanza required
end
