# This file was generated by GoReleaser. DO NOT EDIT.
cask "cool-kit" do
  name "cool-kit"
  desc "CLI toolkit for Coolify deployments"
  homepage "https://github.com/entro314-labs/cool-kit"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cool-kit"

  on_macos do
    on_intel do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_macOS_x86_64.tar.gz"
      sha256 "0cc474aef071b5c380ba61fd80d5e3f46a423aa91258f01ac990b45638426a71"
    end
    on_arm do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_macOS_arm64.tar.gz"
      sha256 "2046cc41c476fe4e44dafbb9f9636a8426387e95aa0f07ddf619c584c4681591"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_linux_x86_64.tar.gz"
      sha256 "29da1acbe5e0e7fcbde0bbb2a0d31ac050dad3e0603af82ebcf77d4124844620"
    end
    on_arm do
      url "https://github.com/entro314-labs/cool-kit/releases/download/v#{version}/cool-kit_#{version}_linux_arm64.tar.gz"
      sha256 "a7109640a33a3da04d2bd2516ca6634536725b6c8cc7795cce3df56d4b297561"
    end
  end

  # No zap stanza required
end
