# This file was generated by GoReleaser. DO NOT EDIT.
cask "devkill" do
  name "devkill"
  desc "A modern TUI to find and delete heavy dev artifacts across languages and platforms."
  homepage "https://github.com/entro314-labs/devkill"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devkill"

  on_macos do
    on_intel do
      url "https://github.com/entro314-labs/devkill/releases/download/v#{version}/devkill_#{version}_macOS_x86_64.tar.gz"
      sha256 "f170070a216955d965350e0d7159a57d33d6fb52bc513fb9ba55e5ed16c25acf"
    end
    on_arm do
      url "https://github.com/entro314-labs/devkill/releases/download/v#{version}/devkill_#{version}_macOS_arm64.tar.gz"
      sha256 "ad67d96ed69a68d5163b653c7f022186f39eb5645286972eeb7a180822f5cc71"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entro314-labs/devkill/releases/download/v#{version}/devkill_#{version}_linux_x86_64.tar.gz"
      sha256 "98a5fc1343e0fa374c2f9d6aeff7339e64e43d0a76d8cd00e5c1fd7137aff5e0"
    end
    on_arm do
      url "https://github.com/entro314-labs/devkill/releases/download/v#{version}/devkill_#{version}_linux_arm64.tar.gz"
      sha256 "69e6ee772226fa39ec1bc449553227327a81c4b8127005b7b8f6edeb534a05ac"
    end
  end

  # No zap stanza required
end
