# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-herd" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "9142014aeab6b479b7e2abc7e7612e4dcfa3704790a4ff83b88c50c51c0d4f47"
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a873f8617b175d396114aac1c94ccc2f888ae004764f97ab3275e465cab37aa6"
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f522cecdda97c9d6847834425d07da203f744f7cd7072f32cf5bec353c1eed6"
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "83dd641080911f4f26706d58619559ecd1e28a8e5b9e06c6cc02181e8da45b13"
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-herd"
  desc "A concurrent Git repository management tool"
  homepage "https://github.com/entro314-labs/git-herd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-herd"

  # No zap stanza required

end
