# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-herd" do
  name "git-herd"
  desc "A concurrent Git repository management tool"
  homepage "https://github.com/entro314-labs/git-herd"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-herd"

  on_macos do
    on_intel do
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_darwin_amd64.tar.gz"
      sha256 "b2c86f87a1523312e5fa8ca79fec8d80d9a878edd17e122cec1b946a4efb34fe"
    end
    on_arm do
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_darwin_arm64.tar.gz"
      sha256 "0ec8cfb8006ecf53dc67d2f2b9b9a9098e67ca9e09fba2f0627233767aa77715"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_linux_amd64.tar.gz"
      sha256 "92e8f9f31e9b2cdc31cc7261c67aa9d52f0349e0895d88e0242e3ac7069b6ad9"
    end
    on_arm do
      url "https://github.com/entro314-labs/git-herd/releases/download/v#{version}/git-herd_#{version}_linux_arm64.tar.gz"
      sha256 "dca41e4ccb93722f9c9095804be352161949a853fdec7e72231b638cc6760cb1"
    end
  end

  # No zap stanza required
end
