# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "meltemi" do
  version "0.8.0"
  on_arm do
    sha256 "051f83efb7bb5e4ebb421d5bd4d8beb0f0cb4bb9282136d302b464cb6ba67351"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "3433e5fe263feaae89722a8c21c9a4ecf3612d251846982767d7704a16b01611"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_x64.dmg"
  end

  name "Meltemi"
  desc "Fast, keyboard-first, cross-platform email client"
  homepage "https://meltemi.email"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "Meltemi.app"
  zap trash: [
    "~/Library/Application Support/com.entro314.meltemi",
    "~/Library/Caches/com.entro314.meltemi",
    "~/Library/Preferences/com.entro314.meltemi.plist",
    "~/Library/Saved Application State/com.entro314.meltemi.savedState",
    "~/Library/WebKit/com.entro314.meltemi",
  ]
end
