# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "meltemi" do
  version "0.3.0"
  on_arm do
    sha256 "1da9c1e60988423d87825c9d126783795eafb0685468336fa85dcb2be24cd3af"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "9d030a22c8fb142d2a2051ddce5ddd8887f6541b1aed17acdaf93edaa0da2c2e"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_x64.dmg"
  end

  name "Meltemi"
  desc "Fast, keyboard-first, cross-platform email client"
  homepage "https://meltemi.email"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "Meltemi.app"
  zap trash: [
    "~/Library/Application Support/com.entro314.meltemi",
    "~/Library/Caches/com.entro314.meltemi",
    "~/Library/Preferences/com.entro314.meltemi.plist",
    "~/Library/Saved Application State/com.entro314.meltemi.savedState",
    "~/Library/WebKit/com.entro314.meltemi",
  ]
end
