# This file is generated by the tauri-release-kit release workflow. DO NOT EDIT.
cask "meltemi" do
  version "0.5.0"
  on_arm do
    sha256 "3614794e2f2103c4b3deb5d973dd4069033bce63c67aa50ed153eac6fc342c6b"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "17286048e7fb3063b8a5332c495cb127433d8f9e4c0ee32156d41a511c448a76"
    url "https://github.com/entro314-labs/meltemi-releases/releases/download/v#{version}/Meltemi_#{version}_x64.dmg"
  end

  name "Meltemi"
  desc "Fast, keyboard-first, cross-platform email client"
  homepage "https://meltemi.email"

  livecheck do
    skip "Updated by the release workflow."
  end

  # The app ships Tauri's built-in updater, so Homebrew must not
  # downgrade it back to the cask version on `brew upgrade`.
  auto_updates true
  # Bare symbol = "this version or newer"; the string comparison form
  # (">= :ventura") is deprecated in Homebrew 4.x and warns on install.
  depends_on macos: :ventura

  app "Meltemi.app"
  zap trash: [
    "~/Library/Application Support/com.entro314.meltemi",
    "~/Library/Caches/com.entro314.meltemi",
    "~/Library/Preferences/com.entro314.meltemi.plist",
    "~/Library/Saved Application State/com.entro314.meltemi.savedState",
    "~/Library/WebKit/com.entro314.meltemi",
  ]
end
