# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHerd < Formula
  desc "A concurrent Git repository management tool"
  homepage "https://github.com/entro314-labs/git-herd"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entro314-labs/git-herd/releases/download/v1.0.5/git-herd_1.0.5_darwin_amd64.tar.gz"
      sha256 "627a079a5a528643ebbe5e80809403089138e2880244ed22b411906b5da970b2"

      def install
        bin.install "git-herd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entro314-labs/git-herd/releases/download/v1.0.5/git-herd_1.0.5_darwin_arm64.tar.gz"
      sha256 "4da62d6ec2fb9fa498c121a9d5f301a6a4897348244136721467971cf35eac68"

      def install
        bin.install "git-herd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entro314-labs/git-herd/releases/download/v1.0.5/git-herd_1.0.5_linux_amd64.tar.gz"
      sha256 "2f35f687f13ad36cf988182a98152fb76a8faf5111013115cc1664b10b153d09"
      def install
        bin.install "git-herd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entro314-labs/git-herd/releases/download/v1.0.5/git-herd_1.0.5_linux_arm64.tar.gz"
      sha256 "bca010a30011691a0405077e96564e322aacc1bd3308d29ead48d1339fd46d40"
      def install
        bin.install "git-herd"
      end
    end
  end

  test do
    system "#{bin}/git-herd", "--version"
  end
end
